{{- if .Values.odoo.enabled }}
{{- if .Values.odoo.postgresql.enabled }}
{{- $secretName := printf "%s-addl-user-passwords" (include "postgresql.v1.primary.fullname" $.Subcharts.odoo.Subcharts.postgresql) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.odoo.postgresql.commonLabels "context" .Subcharts.odoo.Subcharts.postgresql) | nindent 4 }}
  {{- if .Values.odoo.postgresql.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.odoo.postgresql.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $k, $v := .Values.odoo.postgresql.additionalDbs.userPasswords }}
  {{- $secretValuePath := printf "additionalDbs.userPasswords.%s" $k }}
  {{ $k }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" $k "providedValues" (list $secretValuePath) "length" 10 "context" $.Subcharts.odoo.Subcharts.postgresql) }}
  {{- end }}
{{- end }}
{{- end }}
