{{- if .Values.opensearch.enabled }}
{{- if .Values.opensearch.loggingOutput.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "common.names.fullname" .Subcharts.opensearch }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.opensearch.commonLabels "context" .Subcharts.opensearch) | nindent 4 }}
  {{- if .Values.opensearch.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.opensearch.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{ .Values.opensearch.loggingOutput.type }}:
    scheme: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.scheme "context" .Subcharts.opensearch) }}
    host: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.host "context" .Subcharts.opensearch) }}
    port: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.port "context" .Subcharts.opensearch) }}
    user: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.user "context" .Subcharts.opensearch) }}
    password:
      valueFrom:
        secretKeyRef:
          key: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.passwordFrom.secretKeyRef.key "context" .Subcharts.opensearch) }}
          name: {{ include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.passwordFrom.secretKeyRef.name "context" .Subcharts.opensearch) }}
    {{- if .Values.opensearch.loggingOutput.extraConfig }}
    {{- include "common.tplvalues.render" (dict "value" .Values.opensearch.loggingOutput.extraConfig "context" .Subcharts.opensearch) | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
