#!/usr/bin/env bash
# =============================================================================
# Reverse Proxy Node — Phase 1
# =============================================================================
# Steps:
#   R1.1  Resource prereq check (4 vCPU, 16 GB RAM, 64 GB disk)
#   R1.2  apt basics
#   R1.3  ufw — public 22 (admin_cidr), public WG-port; private subnet trusted
#   R1.4  IP forwarding + Wireguard server + N peer configs
#   R1.5  dnsmasq listening on private + WG interface, resolves
#         *.openg2p.internal → rp_private_ip
#   R1.6  Local CA + wildcard self-signed cert *.openg2p.internal
#   R1.7  Nginx — server blocks for rancher and keycloak hostnames,
#         listening on rp_private_ip:443; upstream → compute_private_ip:30080
# =============================================================================

CA_DIR="/etc/openg2p/ca"
CERTS_DIR="/etc/openg2p/certs"
PEER_DIR="/etc/wireguard/peers"

# Resource/OS/network prereqs are covered by lib/shared/preflight.sh.

# ─────────────────────────────────────────────────────────────────────────
# R1.2  apt basics + tools
# ─────────────────────────────────────────────────────────────────────────
rp_install_basics() {
    local step="rp.phase1.basics"
    if skip_if_done "$step" "apt basics"; then return 0; fi

    log_step "R1.2" "Install apt basics, Wireguard, dnsmasq, Nginx"

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y --no-install-recommends \
        curl wget jq openssl dnsutils ca-certificates \
        ufw \
        wireguard-tools \
        dnsmasq \
        nginx

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.3  ufw — public access (SSH + WG), private subnet trusted
# ─────────────────────────────────────────────────────────────────────────
rp_configure_ufw() {
    local step="rp.phase1.ufw"
    if skip_if_done "$step" "ufw rules"; then return 0; fi

    log_step "R1.3" "Configure ufw — public 22/WG, private subnet trusted"

    local admin_cidr=$(cfg "admin_cidr" "0.0.0.0/0")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local private_subnet=$(cfg "private_subnet")

    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing

    # Public
    ufw allow from "$admin_cidr" to any port 22 proto tcp
    ufw allow "${wg_port}/udp" comment "Wireguard"

    # Trusted (private subnet) — anything within the cluster can reach RP
    ufw allow from "$private_subnet"

    # Wireguard peers — full trust (they're authenticated via WG keys)
    ufw allow from "$wg_subnet"

    ufw --force enable

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.4  Wireguard server + peer configs
# ─────────────────────────────────────────────────────────────────────────
rp_setup_wireguard() {
    local step="rp.phase1.wireguard"
    if skip_if_done "$step" "Wireguard server"; then return 0; fi

    log_step "R1.4" "Configure Wireguard server and generate peer configs"

    local rp_pub=$(cfg "rp_public_ip")
    local endpoint=$(cfg "wg_endpoint")
    if [[ -z "$endpoint" ]]; then endpoint="$rp_pub"; fi
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local wg_port=$(cfg "wg_port" "51820")
    local wg_peers=$(cfg "wg_peers" "8")
    local private_subnet=$(cfg "private_subnet")

    # Enable IP forwarding (so WG can route into the private subnet)
    sysctl -w net.ipv4.ip_forward=1 > /dev/null
    grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.conf || \
        echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

    # Parse the WG /16 subnet
    local subnet_base=$(echo "$wg_subnet" | cut -d/ -f1)
    local subnet_mask=$(echo "$wg_subnet" | cut -d/ -f2)
    local octet1=$(echo "$subnet_base" | cut -d. -f1)
    local octet2=$(echo "$subnet_base" | cut -d. -f2)

    mkdir -p /etc/wireguard
    chmod 700 /etc/wireguard

    if [[ -f /etc/wireguard/wg0.conf ]] && systemctl is-active --quiet wg-quick@wg0; then
        log_success "Wireguard already configured and running."
        mark_step_done "$step"
        return 0
    fi

    local server_priv server_pub
    server_priv=$(wg genkey)
    server_pub=$(echo "$server_priv" | wg pubkey)

    local server_ip="${octet1}.${octet2}.0.1"

    # MASQUERADE matches by source CIDR (wg_subnet), not by interface name —
    # Ubuntu 24.04 uses predictable names like ens5/enp0s3, so the older
    # "-o eth+" idiom doesn't match anything on cloud VMs.
    cat > /etc/wireguard/wg0.conf <<EOF
# OpenG2P Wireguard server — auto-generated by openg2p-prod orchestrator
[Interface]
Address = ${server_ip}/${subnet_mask}
ListenPort = ${wg_port}
PrivateKey = ${server_priv}
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s ${wg_subnet} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s ${wg_subnet} -j MASQUERADE
EOF

    # Peer configs — admin laptops route the WG subnet AND the private subnet
    # through the tunnel, so they can reach Nginx and (if needed) compute/storage
    # private IPs directly.
    local allowed_ips="${wg_subnet}, ${private_subnet}"

    # DNS push — RP's WG-side IP runs dnsmasq, resolves *.openg2p.internal.
    local dns_line="DNS = ${server_ip}"

    mkdir -p "$PEER_DIR"
    chmod 700 "$PEER_DIR"

    local n=1 octet3=0 octet4=2
    while [[ $n -le $wg_peers ]]; do
        local peer_priv peer_pub peer_psk peer_ip
        peer_priv=$(wg genkey)
        peer_pub=$(echo "$peer_priv" | wg pubkey)
        peer_psk=$(wg genpsk)
        peer_ip="${octet1}.${octet2}.${octet3}.${octet4}"

        cat >> /etc/wireguard/wg0.conf <<EOF

# peer${n}
[Peer]
PublicKey = ${peer_pub}
PresharedKey = ${peer_psk}
AllowedIPs = ${peer_ip}/32
EOF

        mkdir -p "${PEER_DIR}/peer${n}"
        cat > "${PEER_DIR}/peer${n}/peer${n}.conf" <<EOF
[Interface]
Address = ${peer_ip}/${subnet_mask}
PrivateKey = ${peer_priv}
${dns_line}

[Peer]
PublicKey = ${server_pub}
PresharedKey = ${peer_psk}
Endpoint = ${endpoint}:${wg_port}
AllowedIPs = ${allowed_ips}
PersistentKeepalive = 25
EOF

        octet4=$((octet4 + 1))
        if [[ $octet4 -gt 255 ]]; then
            octet4=0
            octet3=$((octet3 + 1))
        fi
        n=$((n + 1))
    done

    chmod 600 /etc/wireguard/wg0.conf
    chmod -R 600 "$PEER_DIR"
    find "$PEER_DIR" -type d -exec chmod 700 {} \;

    systemctl enable wg-quick@wg0
    systemctl restart wg-quick@wg0

    if ! wg show wg0 &>/dev/null; then
        log_error "Wireguard interface wg0 did not come up" \
                  "wg-quick@wg0 started but wg show fails" \
                  "Inspect logs and config" \
                  "journalctl -u wg-quick@wg0 -n 30; cat /etc/wireguard/wg0.conf"
        exit 1
    fi
    log_success "Wireguard up. Endpoint: ${endpoint}:${wg_port}"
    log_info "Peer configs at ${PEER_DIR}/peer{1..${wg_peers}}/"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.5  dnsmasq — resolve *.openg2p.internal → rp_private_ip
# ─────────────────────────────────────────────────────────────────────────
rp_setup_dnsmasq() {
    local step="rp.phase1.dnsmasq"
    if skip_if_done "$step" "dnsmasq"; then return 0; fi

    log_step "R1.5" "Configure dnsmasq for internal admin DNS"

    local internal=$(cfg "internal_domain" "openg2p.internal")
    local rp_private=$(cfg "rp_private_ip")
    local wg_subnet=$(cfg "wg_subnet" "10.15.0.0/16")
    local wg_server_ip="${wg_subnet%.*.*/*}"
    wg_server_ip="${wg_server_ip}.0.1"   # e.g. 10.15.0.1

    # dnsmasq must not fight with systemd-resolved on port 53.
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        mkdir -p /etc/systemd/resolved.conf.d
        cat > /etc/systemd/resolved.conf.d/openg2p-dnsmasq.conf <<EOF
[Resolve]
DNSStubListener=no
EOF
        ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf 2>/dev/null || true
        systemctl restart systemd-resolved
    fi

    cat > /etc/dnsmasq.d/openg2p.conf <<EOF
# OpenG2P internal DNS — managed by openg2p-prod orchestrator
# All admin tool hostnames resolve to RP's private IP, where Nginx serves them.
address=/${internal}/${rp_private}

# Upstream resolvers for everything else
server=8.8.8.8
server=1.1.1.1

# Listen only on loopback, the WG interface address, and the private subnet.
# We never expose DNS on the public interface.
listen-address=127.0.0.1,${rp_private},${wg_server_ip}
bind-interfaces

# Don't read /etc/hosts (avoids hostname-loopback weirdness on cloud VMs).
no-hosts

log-queries
log-facility=/var/log/dnsmasq-openg2p.log
EOF

    systemctl enable dnsmasq
    systemctl restart dnsmasq

    sleep 1
    local resolved
    resolved=$(dig +short "rancher.${internal}" @127.0.0.1 2>/dev/null || true)
    if [[ "$resolved" != "$rp_private" ]]; then
        log_error "dnsmasq verification failed" \
                  "rancher.${internal} resolved to '${resolved}', expected '${rp_private}'" \
                  "Inspect dnsmasq config and logs" \
                  "dig +short rancher.${internal} @127.0.0.1; tail -30 /var/log/dnsmasq-openg2p.log"
        exit 1
    fi
    log_success "dnsmasq resolves *.${internal} → ${rp_private}"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.6  Local CA + wildcard self-signed cert
# ─────────────────────────────────────────────────────────────────────────
rp_setup_local_ca() {
    local step="rp.phase1.local-ca"
    if skip_if_done "$step" "local CA + wildcard cert"; then return 0; fi

    local internal
    internal=$(cfg "internal_domain" "openg2p.internal")

    log_step "R1.6" "Generate local CA and *.${internal} wildcard cert"

    mkdir -p "$CA_DIR" "$CERTS_DIR"

    if [[ ! -f "${CA_DIR}/ca.key" ]]; then
        log_info "Generating local CA (10-year validity)..."
        openssl genrsa -out "${CA_DIR}/ca.key" 4096 2>/dev/null
        openssl req -x509 -new -nodes \
            -key "${CA_DIR}/ca.key" -sha256 -days 3650 \
            -subj "/C=XX/O=OpenG2P/CN=OpenG2P Local CA (${internal})" \
            -out "${CA_DIR}/ca.crt" 2>/dev/null
        chmod 600 "${CA_DIR}/ca.key"
        log_success "CA at ${CA_DIR}/ca.crt"
    else
        log_info "CA already present at ${CA_DIR}/ca.crt"
    fi

    local cert_dir="${CERTS_DIR}/wildcard.${internal}"
    if [[ -f "${cert_dir}/fullchain.pem" && -f "${cert_dir}/privkey.pem" ]]; then
        log_success "Wildcard cert already exists for *.${internal}"
        mark_step_done "$step"
        return 0
    fi

    mkdir -p "$cert_dir"
    cat > "${cert_dir}/openssl.cnf" <<EOF
[req]
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt             = no
[req_distinguished_name]
C  = XX
O  = OpenG2P
CN = *.${internal}
[v3_req]
basicConstraints = CA:FALSE
keyUsage         = digitalSignature, keyEncipherment
subjectAltName   = @alt_names
[alt_names]
DNS.1 = *.${internal}
DNS.2 = ${internal}
EOF

    openssl genrsa -out "${cert_dir}/privkey.pem" 2048 2>/dev/null
    openssl req -new -key "${cert_dir}/privkey.pem" \
        -config "${cert_dir}/openssl.cnf" \
        -out "${cert_dir}/cert.csr" 2>/dev/null
    openssl x509 -req \
        -in "${cert_dir}/cert.csr" \
        -CA "${CA_DIR}/ca.crt" -CAkey "${CA_DIR}/ca.key" -CAcreateserial \
        -out "${cert_dir}/cert.pem" -days 825 -sha256 \
        -extensions v3_req -extfile "${cert_dir}/openssl.cnf" 2>/dev/null
    cat "${cert_dir}/cert.pem" "${CA_DIR}/ca.crt" > "${cert_dir}/fullchain.pem"
    rm -f "${cert_dir}/cert.csr" "${cert_dir}/openssl.cnf" "${cert_dir}/cert.pem"
    chmod 600 "${cert_dir}/privkey.pem"

    log_success "Wildcard cert at ${cert_dir}/"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# R1.7  Nginx — server blocks for admin tools, listening on private + WG IPs
# ─────────────────────────────────────────────────────────────────────────
rp_setup_nginx() {
    local step="rp.phase1.nginx"
    if skip_if_done "$step" "Nginx config"; then return 0; fi

    log_step "R1.7" "Configure Nginx server blocks for admin tools"

    local internal=$(cfg "internal_domain" "openg2p.internal")
    local rp_private=$(cfg "rp_private_ip")
    local compute_private=$(cfg "compute_private_ip")
    local rancher_host=$(get_rancher_hostname)
    local keycloak_host=$(get_keycloak_hostname)

    local cert="${CERTS_DIR}/wildcard.${internal}/fullchain.pem"
    local key="${CERTS_DIR}/wildcard.${internal}/privkey.pem"

    rm -f /etc/nginx/sites-enabled/default

    cat > /etc/nginx/sites-available/openg2p-infra.conf <<EOF
# OpenG2P admin reverse proxy — managed by openg2p-prod orchestrator.
# Admin tools are reachable ONLY from clients on the private subnet or via
# Wireguard. Public 443 is intentionally NOT bound — exposing admin tools
# publicly is out of scope for v1.

upstream istio_ingress {
    server ${compute_private}:30080;
}

# HTTP -> HTTPS redirect on the private interface
server {
    listen ${rp_private}:80;
    server_name ${rancher_host} ${keycloak_host};
    return 301 https://\$host\$request_uri;
}

server {
    listen ${rp_private}:443 ssl;
    server_name ${rancher_host} ${keycloak_host};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass                http://istio_ingress;
        proxy_http_version        1.1;
        proxy_buffering           on;
        proxy_buffers             8 16k;
        proxy_buffer_size         16k;
        proxy_busy_buffers_size   32k;
        proxy_set_header          Upgrade \$http_upgrade;
        proxy_set_header          Connection "upgrade";
        proxy_set_header          Host \$host;
        proxy_set_header          X-Real-IP \$remote_addr;
        proxy_set_header          X-Forwarded-Host \$host;
        proxy_set_header          X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header          X-Forwarded-Proto https;
        proxy_read_timeout        300s;
        proxy_send_timeout        300s;
    }
}
EOF

    ln -sf /etc/nginx/sites-available/openg2p-infra.conf \
           /etc/nginx/sites-enabled/openg2p-infra.conf

    if ! nginx -t 2>&1 | tail -5; then
        log_error "nginx -t failed" \
                  "Generated config has a syntax error" \
                  "" \
                  "nginx -t"
        exit 1
    fi

    systemctl enable nginx
    # Always full-restart, not reload. The apt nginx package starts the
    # service with a default config (listen 80 on 0.0.0.0), and a SIGHUP
    # reload doesn't reliably transition listen sockets when both the
    # address AND a new SSL port change. Restart guarantees fresh binding.
    systemctl restart nginx

    # Sanity-check the bind: after restart, port 443 must actually be
    # listening or downstream phase 3 cannot reach Rancher.
    if ! ss -tln 2>/dev/null | grep -qE "${rp_private}:443[[:space:]]"; then
        log_error "Nginx restarted but is not listening on ${rp_private}:443" \
                  "Sockets did not bind to the configured address" \
                  "Check 'ss -tlnp', cert files, and nginx error log" \
                  "ls /etc/openg2p/certs/wildcard.${internal}/; journalctl -u nginx -n 30"
        exit 1
    fi
    log_success "Nginx serving https://${rancher_host} and https://${keycloak_host} on ${rp_private}:443"

    mark_step_done "$step"
}

# ─────────────────────────────────────────────────────────────────────────
# Phase entry
# ─────────────────────────────────────────────────────────────────────────
run_rp_phase1() {
    rp_install_basics
    rp_configure_ufw
    rp_setup_wireguard
    rp_setup_dnsmasq
    rp_setup_local_ca
    rp_setup_nginx
}
