{{- if .Values.landing.enabled  }}
{{- if .Values.landing.istio.enabled  }}
{{- if .Values.landing.istio.gateway.enabled  }}
{{- $istioGatewayHostname := include "common.tplvalues.render" (dict "value" .Values.landing.istio.gateway.host "context" $) }}
{{- $mainHostname := include "common.tplvalues.render" (dict "value" .Values.landing.hostname "context" $) }}
{{- $hostname := default $mainHostname $istioGatewayHostname }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}-landing
  labels: {{ include "common.labels.standard" (dict "customLabels" .Values.landing.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.landing.commonAnnotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" .Values.landing.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{ toYaml .Values.landing.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if .Values.landing.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ $hostname | quote }}
    {{- if .Values.landing.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.landing.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ $hostname | quote }}
    tls:
      {{ toYaml (omit .Values.landing.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
