{{- if .Values.kafka.enabled }}
{{- if .Values.kafkaUi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" .Subcharts.kafka }}-ui
  labels: {{ include "common.labels.standard" (dict "customLabels" .Values.kafkaUi.commonLabels "context" .Subcharts.kafka) | nindent 4 }}
  {{- if .Values.kafkaUi.commonAnnotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" .Values.kafkaUi.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  config.yml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.kafkaUi.configYml "context" $) | nindent 4 }}
{{- end }}
{{- end }}
