{{- if .Values.postgresql.enabled }}
{{- if .Values.postgresql.istio.enabled }}
{{- if .Values.postgresql.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.postgresql.commonLabels "context" .Subcharts.postgresql) | nindent 4 }}
  {{- if .Values.postgresql.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.postgresql.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{ toYaml .Values.postgresql.istio.gateway.ingressController | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.postgresql.istio.gateway.port }}
      name: tcp-postgres
      protocol: tcp
    hosts:
    - {{ default .Values.hostname .Values.postgresql.istio.gateway.host | quote }}
    {{- if .Values.postgresql.istio.gateway.tls.enabled }}
    tls:
      {{ toYaml (omit .Values.postgresql.istio.gateway.tls "enabled") | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
